import { useEffect, useState } from "react";
import { useAccessTracking } from "../hooks/useAccessTracking";
import { AccessEscalationBadge } from "./AccessEscalationBadge";
import { Button } from "./ui/button";
import { LogAccessAttemptModal } from "./LogAccessAttemptModal";
import { Plus, UserX, Clock, FileText } from "lucide-react";
import { format } from "date-fns";

interface AccessAttemptPanelProps {
  workOrderId: string;
}

export function AccessAttemptPanel({ workOrderId }: AccessAttemptPanelProps) {
  const { attempts, escalationStatus, fetchAccessAttempts, fetchEscalationStatus } = useAccessTracking(workOrderId);
  const [showLogModal, setShowLogModal] = useState(false);

  useEffect(() => {
    fetchAccessAttempts();
    fetchEscalationStatus();
  }, [fetchAccessAttempts, fetchEscalationStatus]);

  const handleGenerateReport = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const htmlContent = `
      <html>
        <head>
          <title>Access Documentation Report - WO #${workOrderId}</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { font-size: 24px; color: #111; border-bottom: 2px solid #eee; padding-bottom: 16px; margin-bottom: 24px; }
            .header-info { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 32px; background: #f9fafb; padding: 20px; border-radius: 8px; }
            .label { font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; margin-bottom: 4px; }
            .value { font-size: 16px; font-weight: 500; color: #111; }
            .timeline { margin-top: 32px; }
            .attempt { position: relative; padding-left: 24px; margin-bottom: 24px; border-left: 2px solid #e5e7eb; }
            .attempt:last-child { border-left-color: transparent; }
            .attempt::before { content: ''; position: absolute; left: -7px; top: 0; width: 12px; height: 12px; border-radius: 50%; background: #fff; border: 2px solid #6b7280; }
            .attempt-date { font-size: 14px; color: #6b7280; margin-bottom: 4px; }
            .attempt-header { font-size: 16px; font-weight: 600; margin-bottom: 8px; display: flex; align-items: center; gap: 8px; }
            .result-badge { display: inline-block; padding: 2px 8px; border-radius: 99px; font-size: 12px; font-weight: 500; background: #f3f4f6; border: 1px solid #e5e7eb; }
            .notes { background: #fff; border: 1px solid #e5e7eb; padding: 12px; border-radius: 6px; font-size: 14px; line-height: 1.5; color: #374151; }
            .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #9ca3af; text-align: center; }
          </style>
        </head>
        <body>
          <h1>Tenant Access Documentation Report</h1>
          
          <div class="header-info">
            <div>
              <div class="label">Work Order ID</div>
              <div class="value">${workOrderId}</div>
            </div>
            <div>
              <div class="label">Report Generated</div>
              <div class="value">${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}</div>
            </div>
            <div>
              <div class="label">Total Attempts</div>
              <div class="value">${attempts.length}</div>
            </div>
            <div>
              <div class="label">Current Status</div>
              <div class="value" style="color: ${escalationStatus?.escalationStage === 'legal_escalation' ? '#dc2626' : '#111'}">
                ${escalationStatus?.escalationStage?.replace('_', ' ').toUpperCase() || 'N/A'}
              </div>
            </div>
          </div>

          <h2>Attempt Timeline</h2>
          <div class="timeline">
            ${attempts.map(a => `
              <div class="attempt">
                <div class="attempt-date">${new Date(a.attemptDate).toLocaleString()}</div>
                <div class="attempt-header">
                  ${a.attemptMethod.replace('_', ' ').toUpperCase()}
                  <span class="result-badge">${a.contactResult.replace('_', ' ')}</span>
                </div>
                ${a.notes ? `<div class="notes">${a.notes}</div>` : ''}
                <div style="font-size: 12px; color: #9ca3af; margin-top: 4px;">Logged by: ${a.createdBy}</div>
              </div>
            `).join('')}
          </div>

          <div class="footer">
            Generated by Maintenance Operations Center • Internal Use Only
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    // Small timeout to ensure styles load
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  return (
    <div className="bg-gray-50 border rounded-lg p-4 space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <UserX className="h-5 w-5 text-gray-500" />
          <h3 className="font-semibold text-sm">Access Documentation</h3>
        </div>
        {escalationStatus && (
          <AccessEscalationBadge stage={escalationStatus.escalationStage} />
        )}
      </div>

      <div className="space-y-3">
        {attempts.length === 0 ? (
          <div className="text-center py-4 text-sm text-gray-500 italic bg-white rounded border border-dashed">
            No access attempts logged yet.
          </div>
        ) : (
          <div className="space-y-2">
            {attempts.map((attempt) => (
              <div key={attempt.id} className="bg-white p-3 rounded border text-sm shadow-sm">
                <div className="flex justify-between mb-1">
                  <span className="font-medium capitalize">{attempt.attemptMethod.replace('_', ' ')}</span>
                  <span className="text-gray-500 text-xs flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    {format(new Date(attempt.attemptDate), "MMM d, h:mm a")}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className={`px-1.5 py-0.5 rounded text-xs font-medium ${
                    attempt.contactResult === 'successful' ? 'bg-green-100 text-green-700' :
                    attempt.contactResult === 'refused' ? 'bg-red-100 text-red-700' :
                    'bg-gray-100 text-gray-700'
                  }`}>
                    {attempt.contactResult.replace('_', ' ').toUpperCase()}
                  </span>
                  <span className="text-xs text-gray-400">by {attempt.createdBy}</span>
                </div>
                {attempt.notes && (
                  <p className="mt-2 text-gray-600 text-xs border-t pt-2">{attempt.notes}</p>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="flex gap-2">
        <Button 
          variant="outline" 
          size="sm" 
          className="flex-1 bg-white hover:bg-gray-50"
          onClick={() => setShowLogModal(true)}
        >
          <Plus className="h-3 w-3 mr-2" />
          Log Attempt
        </Button>
        
        {attempts.length >= 1 && (
          <Button 
            variant="secondary" 
            size="sm" 
            onClick={handleGenerateReport}
            title="Generate PDF Report for Case Worker"
          >
            <FileText className="h-3 w-3" />
          </Button>
        )}
      </div>

      <LogAccessAttemptModal 
        isOpen={showLogModal} 
        onClose={() => setShowLogModal(false)}
        workOrderId={workOrderId}
      />
    </div>
  );
}
